#!/usr/bin/env bash
#
# sync-prisma-schemas.sh
# ----------------------
# Mirror the canonical resident-service Prisma schema into auth-service so
# every consumer of the shared `resido_core` database sees the same models.
#
# Background
#   - resident-service owns the resido_core schema (it is the only service
#     that runs `prisma db push` against that database).
#   - auth-service ships a generated Prisma client for resido_core so it can
#     READ business profiles, members, blogs, etc. Its schema file must stay
#     in lock-step with the resident-service schema; otherwise `prisma
#     generate` produces a client whose models do not match the real tables
#     and runtime queries silently break (this is exactly how the
#     `linkBusinessProfile` / `Blog.hashtags` columns went missing before).
#
# Usage
#   bash infra/sync-prisma-schemas.sh           # writes + summarises diff
#   bash infra/sync-prisma-schemas.sh --check   # exits non-zero if drift found
#
# Run this whenever you change apps/resident-service/prisma/schema.prisma,
# then commit BOTH files in the same change.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SRC="$REPO_ROOT/apps/resident-service/prisma/schema.prisma"
DEST="$REPO_ROOT/apps/auth-service/prisma/core/schema.prisma"

if [ ! -f "$SRC" ]; then
    echo "❌ Source schema not found at $SRC"
    exit 1
fi

# The destination file lives one directory deeper than the source, so the
# generator output path differs by exactly one `..`. We rewrite it on the fly
# rather than letting the dest copy carry the wrong relative path.
TRANSFORM='s|^  output   = "\.\./node_modules/@resido/resident-client"|  output   = "../../node_modules/@resido/resident-client"|'

# Banner that gets prepended to the destination file so anyone opening it
# immediately understands they should not edit it directly.
BANNER='// ─────────────────────────────────────────────────────────────────────────────
//  ⚠️ AUTO-SYNCED COPY OF apps/resident-service/prisma/schema.prisma  ⚠️
//
//  This file MUST stay byte-identical to the resident-service schema except
//  for the `output` path on the generator below (it lives one directory
//  deeper than the source, so the relative path differs by one `..`).
//
//  Do NOT edit this file directly. Edit the canonical version under
//  apps/resident-service/prisma/schema.prisma and then run:
//
//      bash infra/sync-prisma-schemas.sh
// ─────────────────────────────────────────────────────────────────────────────
'

TMP="$(mktemp)"
{
    printf '%s\n' "$BANNER"
    sed "$TRANSFORM" "$SRC"
} > "$TMP"

if [ "${1:-}" = "--check" ]; then
    if ! diff -q "$TMP" "$DEST" >/dev/null 2>&1; then
        echo "❌ auth-service core schema is out of sync with resident-service."
        echo "   Run:  bash infra/sync-prisma-schemas.sh"
        diff "$DEST" "$TMP" || true
        rm -f "$TMP"
        exit 1
    fi
    rm -f "$TMP"
    echo "✅ auth-service core schema matches resident-service."
    exit 0
fi

mv "$TMP" "$DEST"
echo "✅ Synced:"
echo "   $SRC"
echo "   → $DEST"
